name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-expect
    attributes:
      label: What did you expect to happen?
      description: Tell us, what did you expect to happen?
      placeholder: Tell us what you expected to see!
      value: "I expected this to happen!"
    validations:
        required: false
  - type: dropdown
    id: nodejs-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      options:
        - 16.x
        - 18.x
        - 20.x
        - Other
  - type: dropdown
    validations:
      required: false
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
