name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-docs:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Generate docs with typedoc
        run: npm run docs

      - name: Sync to Github Wiki
        uses: arciera/github-wiki-sync@main

        with:
          build_script: docs
          docs_folder: docs
          message: "chore: update documentation"
