name: Generate docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-docs:
    name: Generate docs
    runs-on: ubuntu-latest

    steps:
      - name: Sync the Github Wiki
        uses: arciera/github-wiki-sync@main

        with:
          build_script: docs
          docs_folder: docs
          message: "chore: update documentation"
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          name: ${{ github.actor }}
