name: Release

on:
    release:
        types: [published]

jobs:
    package-and-upload:
        name: Build and upload
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install dependencies
              run: npm install

            - name: Bundle with NCC
              run: npm run bundle

            - name: Rename bundle
              run: mv build/index.js build/server-${{ github.event.release.tag_name }}.mjs

            - name: Upload to release
              uses: JasonEtco/upload-to-release@master
              with:
                  args: build/server-${{ github.event.release.tag_name }}.mjs text/javascript
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
